imports:
    - { resource: ../../../../drupol/php-conventions/config/php73/grumphp.yml }
    - { resource: tasks.phpcsfixer.config.yml }

parameters:
    # Grumphp license task
    tasks.license.name: BSD-3-Clause
    tasks.license.date_from: 2019
    tasks.license.holder: ECPHP
