imports:
    - { resource: tasks.phpcsfixer.config.yml }
    - { resource: ../../../../vendor/drupol/php-conventions/config/psr12/grumphp.yml }

parameters:
    # Grumphp license task
    tasks.license.name: BSD-3-Clause
    tasks.license.date_from: 2019
    tasks.license.holder: 'ECPHP'
